### ISSUE TITLE
Image showing LoPy antenna connectors

### ISSUE THREAD

**Issue by originalfoo** [ttn-liv/devices#1]
I don't seem to be able to edit the wiki, but here is an quick image I created showing the antenna locations on LoPy (license: CC0 - public domain) for [the LoPy page](https://github.com/ttn-liv/devices/wiki/Getting-started-with-the-PyCom-LoPy#connecting-things-up).

![pycom lopy antennas](https://cloud.githubusercontent.com/assets/1386719/25768522/7c0f424c-31fd-11e7-95df-40d840b52910.png)

**Comment by ajlennon** [comment]
@aubergine10 just spotted the comment about access - I've added it in for you.
